@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PawbookParser" as PawbookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPawbook" as VersionedPawbook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> PawbookParser : parseCommand(undo)
activate PawbookParser

create UndoCommand
PawbookParser -> UndoCommand
activate UndoCommand

UndoCommand --> PawbookParser
deactivate UndoCommand

PawbookParser --> LogicManager : u
deactivate PawbookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoPawbookParser()
activate Model

Model -> VersionedPawbook : undo()
activate VersionedPawbook

VersionedPawbook -> VersionedPawbook :resetData(ReadOnlyPawbook)
VersionedPawbook --> Model :
deactivate VersionedPawbook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
